### ISSUE TITLE
Intellisense for Model's in cshtml files not working.

### ISSUE THREAD

**Issue by tnesbit450** [schneiderpat/aspnet-helper#10]
I believe I have satisfied all of the requirements as you've outlined in the extension configuration instructions.I have updated _ViewImports.cshtml, added [HttpGet] to actions, my Areas folder is in the correct location, and my controllers are named in standard fashion in the Controllers folder. Yet, the intellisence is not working. Thanks!
![screen shot 2017-08-23 at 10 03 29 am](https://user-images.githubusercontent.com/5910797/29628456-5b4bc006-87ea-11e7-91a6-a8da826a8157.png)

**Comment by fdinardo** [comment]
did you try `ctrl+space`?

**Comment by tnesbit450** [comment]
@fdinardo - Thanks for the reply, and I just attempted that no without any success.

**Comment by fdinardo** [comment]
@tnesbit450 I faced a similar situation where another extensions was in conflicts with aspnet-helper extension. 
You can try some things in order to get it work:
1) Make sure that "Language Mode" is set to Razor: you can check this at the bottom right of the status bar.
2) Make sure no other extension are in conflicts with aspnet-helper: usually extensions targeting html files can make conflicts with aspnet-helper ( I faced a similar issue with [this](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css) extension.
3) Make sure to have _Intellisense_ [correctly installed](https://code.visualstudio.com/docs/editor/intellisense).

Let me know. :)

**Comment by tnesbit450** [comment]
@fdinardo - You're awesome! Can't believe I didn't notice this, I wasn't in Razor mode. That fixed it!

**Comment by fdinardo** [comment]
@tnesbit450 I'll be honest with you. I'm just a user of this amazing tool, but I like it so much that I would keep it updated. I think the owner is busy and the extensions is not updated (it seems like it's dropped)
I made a pull request that fixes an issue with virtual and nullable properties (see #12)

About your question the answer seems to be: "NO". But If I have time to tackle it I will make another pull request for this that to me it's really helpful. 

Just last thing: I have no clue on how contact the owner. Through github he/she doesn't responds and he/she seems to be offline for a long time.

**Comment by fdinardo** [comment]
@schneiderpat I think this can be closed.
